# Generated by Django 5.0.1 on 2024-01-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_gameserver1'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameServer12313',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('player1', models.IntegerField()),
                ('player2', models.IntegerField()),
                ('stone', models.IntegerField()),
                ('paper', models.IntegerField()),
                ('scissors', models.IntegerField()),
                ('player1Win', models.IntegerField()),
                ('player2Win', models.IntegerField()),
            ],
        ),
    ]
