# Generated by Django 5.0.1 on 2024-01-14 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_gameserver12313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameServer1',
        ),
        migrations.DeleteModel(
            name='GameServer12313',
        ),
    ]
