# Generated by Django 5.0.1 on 2024-01-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_gameserver1_delete_gameserver12313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameserver',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='gameserver',
            name='scissors',
        ),
        migrations.RemoveField(
            model_name='gameserver',
            name='stone',
        ),
        migrations.AddField(
            model_name='gameserver',
            name='ans_player1',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameserver',
            name='ans_player2',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameserver',
            name='winner',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
