# Generated by Django 5.0.1 on 2024-01-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_gameserver_paper_remove_gameserver_scissors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserver',
            name='cnt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
