# Generated by Django 5.0.1 on 2024-01-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_gameserver_cnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameserver',
            name='cnt',
        ),
    ]
