# Generated by Django 5.0.1 on 2024-01-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_gameserver_cnt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameserver',
            old_name='cnt',
            new_name='player1_cnt',
        ),
        migrations.AddField(
            model_name='gameserver',
            name='player2_cnt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
