# Generated by Django 5.0.1 on 2024-01-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_cnt_gameserver_player1_cnt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameserver',
            old_name='player1_cnt',
            new_name='cnt',
        ),
        migrations.RemoveField(
            model_name='gameserver',
            name='player2_cnt',
        ),
    ]
