# Generated by Django 5.0.1 on 2024-01-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_rename_player1_cnt_gameserver_cnt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserver',
            name='player1_click',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameserver',
            name='player2_click',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
