# Generated by Django 5.0.1 on 2024-01-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_gameserver_player1_click_gameserver_player2_click'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserver',
            name='change',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
