# Generated by Django 5.0.1 on 2024-01-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_gameserver_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserver',
            name='player1name',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameserver',
            name='player2name',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
