# Generated by Django 5.0.1 on 2024-01-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_gameserver_player1name_gameserver_player2name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameserver',
            name='player1name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='player2name',
            field=models.CharField(max_length=50),
        ),
    ]
