# Generated by Django 5.0.1 on 2024-01-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_gameserver_player1name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameserver',
            name='player1name',
        ),
        migrations.RemoveField(
            model_name='gameserver',
            name='player2name',
        ),
    ]
