# Generated by Django 5.0.1 on 2024-01-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_gameserver_player1name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserver',
            name='player1name',
            field=models.CharField(default='aa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameserver',
            name='player2name',
            field=models.CharField(default='aa', max_length=50),
            preserve_default=False,
        ),
    ]
