# Generated by Django 5.0.1 on 2024-01-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_gameserver_player1name_gameserver_player2name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserver',
            name='emoji',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
