# Generated by Django 5.0.1 on 2024-01-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_gameserver_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserver',
            name='emoji2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
