# Generated by Django 5.0.1 on 2024-01-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_gameserver_emoji2'),
    ]

    operations = [
        migrations.CreateModel(
            name='reload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reloads', models.IntegerField()),
            ],
        ),
    ]
