# Generated by Django 5.0.1 on 2024-01-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_reload'),
    ]

    operations = [
        migrations.AddField(
            model_name='reload',
            name='name',
            field=models.CharField(default='z', max_length=50),
            preserve_default=False,
        ),
    ]
