# Generated by Django 5.0.1 on 2024-01-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_reload_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reload',
            old_name='name',
            new_name='player1',
        ),
        migrations.AddField(
            model_name='reload',
            name='player2',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
