# Generated by Django 5.0.1 on 2024-01-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_rename_name_reload_player1_reload_player2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reload',
        ),
        migrations.AddField(
            model_name='user',
            name='change',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
