# Generated by Django 5.0.1 on 2024-02-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_delete_reload_user_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emoji',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
